/**
 * PC.2a — Calculator fixtures (v1 seed: 10 high-yield calcs)
 *
 * Payload shape matches `calculators.createCalc` tRPC input:
 *   { def: CalcDef, inputs: CalcInput[], scoring: CalcScoring[], bands: CalcBand[] }
 *
 * Scoring engine (pure TS, deterministic):
 *   - 'sum'         : if input matches when_value (or boolean true when when_value is null), add points.
 *   - 'weighted'    : points × numeric input value.
 *   - 'conditional' : evaluate formula_expr (single binary compare only, e.g. "age >= 65").
 *
 * Prose (narrative interpretation) is generated by Qwen at runtime — NOT in this fixture.
 * The `interpretation_default` on each band is the baseline shown before Qwen responds.
 *
 * Chart prefill: fields with `chart_source_path` get a "📋 from chart" badge at runtime.
 * Paths are dot-notation against the chart-context payload shipped in PC.2b.
 *
 * MELD-banded-v1: the engine has no ln(); PC.2a ships a banded approximation. The exact
 * MELD formula (9.57·ln(Cr) + 3.78·ln(Bili) + 11.2·ln(INR) + 6.43) ships in PC.2c when
 * Qwen interpret + server-side formula helper land together.
 */

export type CalcFixtureInput = {
  key: string;
  label: string;
  helper_text?: string | null;
  type: 'boolean' | 'number' | 'select' | 'date';
  unit?: string | null;
  options?: Array<{ value: string; label: string }> | { min?: number; max?: number; step?: number } | null;
  chart_source_path?: string | null;
  required?: boolean;
  display_order?: number;
};
export type CalcFixtureScoring = {
  rule_type: 'sum' | 'weighted' | 'conditional';
  input_key: string;
  when_value?: string | null;
  points: number;
  formula_expr?: string | null;
  display_order?: number;
};
export type CalcFixtureBand = {
  band_key: string;
  label: string;
  min_score: number;
  max_score: number | null;
  color: 'green' | 'yellow' | 'red' | 'grey';
  interpretation_default?: string | null;
  display_order?: number;
};
export type CalcFixtureDef = {
  slug: string;
  name: string;
  specialty: string;
  short_description?: string | null;
  long_description?: string | null;
  version?: string;
  is_active?: boolean;
  pin_default_for_roles?: string[];
  source_citation?: string | null;
  /** PC.2c1: named-formula key in scoring-engine FORMULAS registry. */
  formula_ref?: string | null;
};
export type CalcFixture = {
  def: CalcFixtureDef;
  inputs: CalcFixtureInput[];
  scoring: CalcFixtureScoring[];
  bands: CalcFixtureBand[];
};

// ─── 1. CHA2DS2-VASc ───────────────────────────────────────────
const CHA2DS2_VASC: CalcFixture = {
  def: {
    slug: 'cha2ds2-vasc',
    name: 'CHA₂DS₂-VASc',
    specialty: 'cardiology',
    short_description: 'Stroke risk in non-valvular atrial fibrillation.',
    long_description: 'Estimates 1-year stroke risk in patients with AF. Score ≥2 (men) or ≥3 (women) generally warrants oral anticoagulation (guideline-dependent).',
    version: '1.0',
    pin_default_for_roles: ['doctor', 'rmo', 'registrar', 'consultant', 'cardiologist'],
    source_citation: 'Lip GY et al., Chest 2010;137:263-72. ESC AF Guidelines 2020.',
  },
  inputs: [
    { key: 'chf_hx',        label: 'Congestive heart failure history',          type: 'boolean', chart_source_path: 'conditions.chf',            display_order: 10 },
    { key: 'htn_hx',        label: 'Hypertension history',                      type: 'boolean', chart_source_path: 'conditions.hypertension',   display_order: 20 },
    { key: 'age_ge75',      label: 'Age ≥75 years',                              type: 'boolean', chart_source_path: 'patient.age_ge75',          display_order: 30 },
    { key: 'dm_hx',         label: 'Diabetes mellitus',                          type: 'boolean', chart_source_path: 'conditions.diabetes',      display_order: 40 },
    { key: 'stroke_tia_hx', label: 'Prior stroke / TIA / thromboembolism',       type: 'boolean', chart_source_path: 'conditions.stroke_tia',    display_order: 50 },
    { key: 'vascular_hx',   label: 'Vascular disease (prior MI, PAD, aortic plaque)', type: 'boolean', chart_source_path: 'conditions.vascular', display_order: 60 },
    { key: 'age_65_74',     label: 'Age 65–74 years',                            type: 'boolean', chart_source_path: 'patient.age_65_74',        display_order: 70 },
    { key: 'female',        label: 'Female sex',                                 type: 'boolean', chart_source_path: 'patient.female',           display_order: 80 },
  ],
  scoring: [
    { rule_type: 'sum', input_key: 'chf_hx',        points: 1, display_order: 10 },
    { rule_type: 'sum', input_key: 'htn_hx',        points: 1, display_order: 20 },
    { rule_type: 'sum', input_key: 'age_ge75',      points: 2, display_order: 30 },
    { rule_type: 'sum', input_key: 'dm_hx',         points: 1, display_order: 40 },
    { rule_type: 'sum', input_key: 'stroke_tia_hx', points: 2, display_order: 50 },
    { rule_type: 'sum', input_key: 'vascular_hx',   points: 1, display_order: 60 },
    { rule_type: 'sum', input_key: 'age_65_74',     points: 1, display_order: 70 },
    { rule_type: 'sum', input_key: 'female',        points: 1, display_order: 80 },
  ],
  bands: [
    { band_key: 'low',           label: 'Low risk',           min_score: 0, max_score: 0,    color: 'green',  interpretation_default: 'Annual stroke risk ~0.2%. Anticoagulation generally not recommended.', display_order: 10 },
    { band_key: 'low_moderate',  label: 'Low-moderate risk',  min_score: 1, max_score: 1,    color: 'yellow', interpretation_default: 'Annual stroke risk ~0.6%. Consider anticoagulation (men score 1) or none (women score 1); individualise.', display_order: 20 },
    { band_key: 'moderate_high', label: 'Moderate-high risk', min_score: 2, max_score: 3,    color: 'yellow', interpretation_default: 'Annual stroke risk ~2.2–3.2%. Oral anticoagulation generally recommended.', display_order: 30 },
    { band_key: 'high',          label: 'High risk',          min_score: 4, max_score: null, color: 'red',    interpretation_default: 'Annual stroke risk ≥4%. Oral anticoagulation strongly recommended unless contraindicated.', display_order: 40 },
  ],
};

// ─── 2. HAS-BLED ───────────────────────────────────────────────
const HAS_BLED: CalcFixture = {
  def: {
    slug: 'has-bled',
    name: 'HAS-BLED',
    specialty: 'cardiology',
    short_description: 'Major bleeding risk on anticoagulation in AF.',
    long_description: 'Estimates 1-year major bleeding risk in AF patients on anticoagulation. Score ≥3 flags high bleeding risk — does not preclude anticoagulation, but mandates closer monitoring and modifiable-factor review.',
    version: '1.0',
    pin_default_for_roles: ['doctor', 'rmo', 'registrar', 'consultant', 'cardiologist'],
    source_citation: 'Pisters R et al., Chest 2010;138:1093-1100.',
  },
  inputs: [
    { key: 'htn_uncontrolled', label: 'Hypertension (uncontrolled, SBP >160)',         type: 'boolean', chart_source_path: 'vitals.sbp_gt_160',         display_order: 10 },
    { key: 'abn_renal',        label: 'Abnormal renal function (Cr >2.3 or dialysis)', type: 'boolean', chart_source_path: 'labs.renal_abnormal',       display_order: 20 },
    { key: 'abn_liver',        label: 'Abnormal liver function',                       type: 'boolean', chart_source_path: 'labs.liver_abnormal',       display_order: 30 },
    { key: 'stroke_hx',        label: 'Prior stroke',                                  type: 'boolean', chart_source_path: 'conditions.stroke',         display_order: 40 },
    { key: 'bleeding_hx',      label: 'Prior bleeding or predisposition',              type: 'boolean', chart_source_path: 'conditions.bleeding',       display_order: 50 },
    { key: 'labile_inr',       label: 'Labile INR (TTR <60%)',                         type: 'boolean',                                                 display_order: 60 },
    { key: 'age_gt65',         label: 'Age >65 years',                                 type: 'boolean', chart_source_path: 'patient.age_gt65',          display_order: 70 },
    { key: 'drugs_antiplatelet', label: 'Drugs concurrently (antiplatelet / NSAID)',   type: 'boolean', chart_source_path: 'medications.bleeding_risk', display_order: 80 },
    { key: 'alcohol_ge8',      label: 'Alcohol ≥8 drinks / week',                      type: 'boolean',                                                 display_order: 90 },
  ],
  scoring: [
    { rule_type: 'sum', input_key: 'htn_uncontrolled',   points: 1, display_order: 10 },
    { rule_type: 'sum', input_key: 'abn_renal',          points: 1, display_order: 20 },
    { rule_type: 'sum', input_key: 'abn_liver',          points: 1, display_order: 30 },
    { rule_type: 'sum', input_key: 'stroke_hx',          points: 1, display_order: 40 },
    { rule_type: 'sum', input_key: 'bleeding_hx',        points: 1, display_order: 50 },
    { rule_type: 'sum', input_key: 'labile_inr',         points: 1, display_order: 60 },
    { rule_type: 'sum', input_key: 'age_gt65',           points: 1, display_order: 70 },
    { rule_type: 'sum', input_key: 'drugs_antiplatelet', points: 1, display_order: 80 },
    { rule_type: 'sum', input_key: 'alcohol_ge8',        points: 1, display_order: 90 },
  ],
  bands: [
    { band_key: 'low',      label: 'Low bleeding risk',      min_score: 0, max_score: 1,    color: 'green',  interpretation_default: 'Major-bleed risk ~1.13% per year. Standard monitoring.', display_order: 10 },
    { band_key: 'moderate', label: 'Moderate bleeding risk', min_score: 2, max_score: 2,    color: 'yellow', interpretation_default: 'Major-bleed risk ~1.88% per year. Address modifiable risk factors.', display_order: 20 },
    { band_key: 'high',     label: 'High bleeding risk',     min_score: 3, max_score: null, color: 'red',    interpretation_default: 'Major-bleed risk ≥3.74% per year. Does NOT preclude anticoagulation — trigger closer monitoring and aggressive modifiable-factor correction.', display_order: 30 },
  ],
};

export const CALCULATOR_FIXTURES_PART1: CalcFixture[] = [CHA2DS2_VASC, HAS_BLED];

// ─── 3. HEART Score (chest pain) ───────────────────────────────
const HEART_SCORE: CalcFixture = {
  def: {
    slug: 'heart-score',
    name: 'HEART Score for chest pain',
    specialty: 'emergency',
    short_description: '6-week risk of MACE in ED chest-pain patients.',
    long_description: 'Risk-stratifies undifferentiated chest-pain patients in the emergency department for 6-week major adverse cardiac events (MACE). Low score (0-3) supports early discharge; high score (≥7) supports admission/invasive workup.',
    version: '1.0',
    pin_default_for_roles: ['doctor', 'rmo', 'registrar', 'consultant', 'emergency_physician'],
    source_citation: 'Six AJ, Backus BE, Kelder JC. Neth Heart J 2008;16:191-6.',
  },
  inputs: [
    { key: 'history',       label: 'History',
      helper_text: 'Suspicion from history (typical features of ACS).',
      type: 'select',
      options: [
        { value: 'slightly',     label: 'Slightly suspicious (0)' },
        { value: 'moderately',   label: 'Moderately suspicious (1)' },
        { value: 'highly',       label: 'Highly suspicious (2)' },
      ],
      display_order: 10 },
    { key: 'ecg',           label: 'ECG',
      type: 'select',
      options: [
        { value: 'normal',       label: 'Normal (0)' },
        { value: 'nonspecific',  label: 'Non-specific repolarisation (1)' },
        { value: 'st_deviation', label: 'Significant ST deviation (2)' },
      ],
      display_order: 20 },
    { key: 'age',           label: 'Age',
      type: 'select', chart_source_path: 'patient.age_band',
      options: [
        { value: 'lt_45',   label: '<45 years (0)' },
        { value: '45_64',   label: '45–64 years (1)' },
        { value: 'ge_65',   label: '≥65 years (2)' },
      ],
      display_order: 30 },
    { key: 'risk_factors',  label: 'Risk factors',
      helper_text: 'HTN, hyperlipidaemia, DM, obesity (BMI >30), smoking, family hx premature CAD, known atherosclerotic disease.',
      type: 'select',
      options: [
        { value: 'none',    label: 'No known risk factors (0)' },
        { value: 'one_two', label: '1–2 risk factors (1)' },
        { value: 'ge_three_or_cad', label: '≥3 risk factors or known atherosclerotic disease (2)' },
      ],
      display_order: 40 },
    { key: 'troponin',      label: 'Initial troponin',
      type: 'select', chart_source_path: 'labs.troponin_band',
      options: [
        { value: 'normal',       label: 'Normal (≤ normal limit) (0)' },
        { value: '1_to_3x',      label: '1–3× normal limit (1)' },
        { value: 'gt_3x',        label: '>3× normal limit (2)' },
      ],
      display_order: 50 },
  ],
  scoring: [
    { rule_type: 'sum', input_key: 'history',      when_value: 'slightly',          points: 0, display_order: 10 },
    { rule_type: 'sum', input_key: 'history',      when_value: 'moderately',        points: 1, display_order: 11 },
    { rule_type: 'sum', input_key: 'history',      when_value: 'highly',            points: 2, display_order: 12 },
    { rule_type: 'sum', input_key: 'ecg',          when_value: 'normal',            points: 0, display_order: 20 },
    { rule_type: 'sum', input_key: 'ecg',          when_value: 'nonspecific',       points: 1, display_order: 21 },
    { rule_type: 'sum', input_key: 'ecg',          when_value: 'st_deviation',      points: 2, display_order: 22 },
    { rule_type: 'sum', input_key: 'age',          when_value: 'lt_45',             points: 0, display_order: 30 },
    { rule_type: 'sum', input_key: 'age',          when_value: '45_64',             points: 1, display_order: 31 },
    { rule_type: 'sum', input_key: 'age',          when_value: 'ge_65',             points: 2, display_order: 32 },
    { rule_type: 'sum', input_key: 'risk_factors', when_value: 'none',              points: 0, display_order: 40 },
    { rule_type: 'sum', input_key: 'risk_factors', when_value: 'one_two',           points: 1, display_order: 41 },
    { rule_type: 'sum', input_key: 'risk_factors', when_value: 'ge_three_or_cad',   points: 2, display_order: 42 },
    { rule_type: 'sum', input_key: 'troponin',     when_value: 'normal',            points: 0, display_order: 50 },
    { rule_type: 'sum', input_key: 'troponin',     when_value: '1_to_3x',           points: 1, display_order: 51 },
    { rule_type: 'sum', input_key: 'troponin',     when_value: 'gt_3x',             points: 2, display_order: 52 },
  ],
  bands: [
    { band_key: 'low',      label: 'Low risk',      min_score: 0, max_score: 3,    color: 'green',  interpretation_default: '6-week MACE ~1.7%. Early discharge from ED is generally supported.', display_order: 10 },
    { band_key: 'moderate', label: 'Moderate risk', min_score: 4, max_score: 6,    color: 'yellow', interpretation_default: '6-week MACE ~16.6%. Admission for observation / non-invasive testing typically indicated.', display_order: 20 },
    { band_key: 'high',     label: 'High risk',     min_score: 7, max_score: null, color: 'red',    interpretation_default: '6-week MACE ~50.1%. Invasive workup (early angiography) generally indicated.', display_order: 30 },
  ],
};

// ─── 4. Wells DVT ──────────────────────────────────────────────
const WELLS_DVT: CalcFixture = {
  def: {
    slug: 'wells-dvt',
    name: 'Wells Score for DVT',
    specialty: 'emergency',
    short_description: 'Pretest probability of deep-vein thrombosis.',
    long_description: 'Risk-stratifies patients with suspected DVT for pretest probability. Low score → D-dimer rules out; moderate/high → duplex ultrasound.',
    version: '1.0',
    pin_default_for_roles: ['doctor', 'rmo', 'registrar', 'emergency_physician'],
    source_citation: 'Wells PS et al., NEJM 2003;349:1227-35.',
  },
  inputs: [
    { key: 'active_cancer',     label: 'Active cancer (treatment within 6 mo or palliative)', type: 'boolean', chart_source_path: 'conditions.active_cancer', display_order: 10 },
    { key: 'paralysis_cast',    label: 'Paralysis, paresis, or recent plaster immobilisation of legs', type: 'boolean', display_order: 20 },
    { key: 'bedridden_surgery', label: 'Bedridden ≥3 days or major surgery within 12 weeks',  type: 'boolean', display_order: 30 },
    { key: 'tenderness_veins',  label: 'Localised tenderness along deep venous system',       type: 'boolean', display_order: 40 },
    { key: 'entire_leg_swollen',label: 'Entire leg swollen',                                  type: 'boolean', display_order: 50 },
    { key: 'calf_swelling_gt3', label: 'Calf swelling >3 cm vs asymptomatic leg (10 cm below tibial tuberosity)', type: 'boolean', display_order: 60 },
    { key: 'pitting_edema',     label: 'Pitting oedema confined to symptomatic leg',          type: 'boolean', display_order: 70 },
    { key: 'collateral_veins',  label: 'Collateral superficial veins (non-varicose)',         type: 'boolean', display_order: 80 },
    { key: 'prior_dvt',         label: 'Previously documented DVT',                           type: 'boolean', chart_source_path: 'conditions.prior_dvt', display_order: 90 },
    { key: 'alt_dx_likely',     label: 'Alternative diagnosis at least as likely as DVT',     type: 'boolean', display_order: 100 },
  ],
  scoring: [
    { rule_type: 'sum', input_key: 'active_cancer',      points: 1,  display_order: 10 },
    { rule_type: 'sum', input_key: 'paralysis_cast',     points: 1,  display_order: 20 },
    { rule_type: 'sum', input_key: 'bedridden_surgery',  points: 1,  display_order: 30 },
    { rule_type: 'sum', input_key: 'tenderness_veins',   points: 1,  display_order: 40 },
    { rule_type: 'sum', input_key: 'entire_leg_swollen', points: 1,  display_order: 50 },
    { rule_type: 'sum', input_key: 'calf_swelling_gt3',  points: 1,  display_order: 60 },
    { rule_type: 'sum', input_key: 'pitting_edema',      points: 1,  display_order: 70 },
    { rule_type: 'sum', input_key: 'collateral_veins',   points: 1,  display_order: 80 },
    { rule_type: 'sum', input_key: 'prior_dvt',          points: 1,  display_order: 90 },
    { rule_type: 'sum', input_key: 'alt_dx_likely',      points: -2, display_order: 100 },
  ],
  bands: [
    { band_key: 'low',      label: 'Low probability',      min_score: -2, max_score: 0,    color: 'green',  interpretation_default: 'DVT probability ~5%. Negative D-dimer rules out DVT; positive D-dimer → duplex ultrasound.', display_order: 10 },
    { band_key: 'moderate', label: 'Moderate probability', min_score: 1,  max_score: 2,    color: 'yellow', interpretation_default: 'DVT probability ~17%. Proceed to duplex ultrasound.', display_order: 20 },
    { band_key: 'high',     label: 'High probability',     min_score: 3,  max_score: null, color: 'red',    interpretation_default: 'DVT probability ≥53%. Proceed directly to duplex ultrasound; consider empirical anticoagulation while awaiting imaging if low bleed risk.', display_order: 30 },
  ],
};

// ─── 5. Wells PE ───────────────────────────────────────────────
const WELLS_PE: CalcFixture = {
  def: {
    slug: 'wells-pe',
    name: 'Wells Score for PE',
    specialty: 'emergency',
    short_description: 'Pretest probability of pulmonary embolism.',
    long_description: 'Risk-stratifies patients with suspected PE. Score ≤4 + negative D-dimer rules out PE (combined with PERC or age-adjusted D-dimer); >4 → imaging (CTPA).',
    version: '1.0',
    pin_default_for_roles: ['doctor', 'rmo', 'registrar', 'emergency_physician'],
    source_citation: 'Wells PS et al., Ann Intern Med 2001;135:98-107.',
  },
  inputs: [
    { key: 'dvt_signs',       label: 'Clinical signs & symptoms of DVT', type: 'boolean', display_order: 10 },
    { key: 'pe_most_likely',  label: 'PE is #1 diagnosis, or equally likely', type: 'boolean', display_order: 20 },
    { key: 'hr_gt_100',       label: 'Heart rate >100 bpm',              type: 'boolean', chart_source_path: 'vitals.hr_gt_100', display_order: 30 },
    { key: 'immob_surgery_4w',label: 'Immobilisation ≥3d or surgery within 4 weeks', type: 'boolean', display_order: 40 },
    { key: 'prior_vte',       label: 'Previous objectively-diagnosed PE or DVT', type: 'boolean', chart_source_path: 'conditions.prior_vte', display_order: 50 },
    { key: 'hemoptysis',      label: 'Haemoptysis',                      type: 'boolean', display_order: 60 },
    { key: 'malignancy',      label: 'Malignancy (treatment within 6 mo or palliative)', type: 'boolean', chart_source_path: 'conditions.active_cancer', display_order: 70 },
  ],
  scoring: [
    { rule_type: 'sum', input_key: 'dvt_signs',        points: 3,   display_order: 10 },
    { rule_type: 'sum', input_key: 'pe_most_likely',   points: 3,   display_order: 20 },
    { rule_type: 'sum', input_key: 'hr_gt_100',        points: 1.5, display_order: 30 },
    { rule_type: 'sum', input_key: 'immob_surgery_4w', points: 1.5, display_order: 40 },
    { rule_type: 'sum', input_key: 'prior_vte',        points: 1.5, display_order: 50 },
    { rule_type: 'sum', input_key: 'hemoptysis',       points: 1,   display_order: 60 },
    { rule_type: 'sum', input_key: 'malignancy',       points: 1,   display_order: 70 },
  ],
  bands: [
    { band_key: 'low',      label: 'Low probability',      min_score: 0,   max_score: 1.5,  color: 'green',  interpretation_default: 'PE probability ~1.3%. Apply PERC or age-adjusted D-dimer to rule out.', display_order: 10 },
    { band_key: 'moderate', label: 'Moderate probability', min_score: 2,   max_score: 6,    color: 'yellow', interpretation_default: 'PE probability ~16.2%. Use D-dimer to triage; positive → CTPA.', display_order: 20 },
    { band_key: 'high',     label: 'High probability',     min_score: 6.5, max_score: null, color: 'red',    interpretation_default: 'PE probability ~40.6%. Go directly to CTPA; consider empirical anticoagulation while awaiting imaging if low bleed risk.', display_order: 30 },
  ],
};

// ─── 6. GCS (Glasgow Coma Scale) ───────────────────────────────
const GCS: CalcFixture = {
  def: {
    slug: 'gcs',
    name: 'Glasgow Coma Scale',
    specialty: 'neurology',
    short_description: 'Conscious-level assessment (3–15).',
    long_description: 'Three-component neurological scale: eye-opening (1–4), verbal (1–5), motor (1–6). 13–15 mild, 9–12 moderate, ≤8 severe (intubation usually indicated).',
    version: '1.0',
    pin_default_for_roles: ['doctor', 'rmo', 'registrar', 'consultant', 'emergency_physician', 'neurologist', 'nurse', 'charge_nurse'],
    source_citation: 'Teasdale G, Jennett B. Lancet 1974;2:81-4.',
  },
  inputs: [
    { key: 'eye',    label: 'Eye opening',
      type: 'select', chart_source_path: 'neuro.gcs_eye',
      options: [
        { value: '4', label: 'Spontaneous (4)' },
        { value: '3', label: 'To voice (3)' },
        { value: '2', label: 'To pain (2)' },
        { value: '1', label: 'None (1)' },
      ],
      display_order: 10 },
    { key: 'verbal', label: 'Verbal response',
      type: 'select', chart_source_path: 'neuro.gcs_verbal',
      options: [
        { value: '5', label: 'Oriented (5)' },
        { value: '4', label: 'Confused (4)' },
        { value: '3', label: 'Inappropriate words (3)' },
        { value: '2', label: 'Incomprehensible sounds (2)' },
        { value: '1', label: 'None (1)' },
      ],
      display_order: 20 },
    { key: 'motor',  label: 'Motor response',
      type: 'select', chart_source_path: 'neuro.gcs_motor',
      options: [
        { value: '6', label: 'Obeys commands (6)' },
        { value: '5', label: 'Localises pain (5)' },
        { value: '4', label: 'Withdraws from pain (4)' },
        { value: '3', label: 'Abnormal flexion (decorticate) (3)' },
        { value: '2', label: 'Abnormal extension (decerebrate) (2)' },
        { value: '1', label: 'None (1)' },
      ],
      display_order: 30 },
  ],
  scoring: [
    { rule_type: 'sum', input_key: 'eye',    when_value: '1', points: 1, display_order: 10 },
    { rule_type: 'sum', input_key: 'eye',    when_value: '2', points: 2, display_order: 11 },
    { rule_type: 'sum', input_key: 'eye',    when_value: '3', points: 3, display_order: 12 },
    { rule_type: 'sum', input_key: 'eye',    when_value: '4', points: 4, display_order: 13 },
    { rule_type: 'sum', input_key: 'verbal', when_value: '1', points: 1, display_order: 20 },
    { rule_type: 'sum', input_key: 'verbal', when_value: '2', points: 2, display_order: 21 },
    { rule_type: 'sum', input_key: 'verbal', when_value: '3', points: 3, display_order: 22 },
    { rule_type: 'sum', input_key: 'verbal', when_value: '4', points: 4, display_order: 23 },
    { rule_type: 'sum', input_key: 'verbal', when_value: '5', points: 5, display_order: 24 },
    { rule_type: 'sum', input_key: 'motor',  when_value: '1', points: 1, display_order: 30 },
    { rule_type: 'sum', input_key: 'motor',  when_value: '2', points: 2, display_order: 31 },
    { rule_type: 'sum', input_key: 'motor',  when_value: '3', points: 3, display_order: 32 },
    { rule_type: 'sum', input_key: 'motor',  when_value: '4', points: 4, display_order: 33 },
    { rule_type: 'sum', input_key: 'motor',  when_value: '5', points: 5, display_order: 34 },
    { rule_type: 'sum', input_key: 'motor',  when_value: '6', points: 6, display_order: 35 },
  ],
  bands: [
    { band_key: 'severe',   label: 'Severe',   min_score: 3,  max_score: 8,  color: 'red',    interpretation_default: 'Severe brain injury. Intubation for airway protection generally indicated. Urgent imaging + neurosurgical review.', display_order: 10 },
    { band_key: 'moderate', label: 'Moderate', min_score: 9,  max_score: 12, color: 'yellow', interpretation_default: 'Moderate brain injury. Close monitoring; serial GCS; consider imaging.', display_order: 20 },
    { band_key: 'mild',     label: 'Mild',     min_score: 13, max_score: 15, color: 'green',  interpretation_default: 'Mild impairment. Monitor trend; investigate cause if any decline.', display_order: 30 },
  ],
};

// ─── 7. NEWS2 ──────────────────────────────────────────────────
const NEWS2: CalcFixture = {
  def: {
    slug: 'news2',
    name: 'NEWS2',
    specialty: 'general_medicine',
    short_description: 'National Early Warning Score 2 (deterioration).',
    long_description: 'UK RCP early-warning score for acute illness. Triggers escalation: ≥5 = urgent review; ≥7 = emergency response. Oxygen scale 1 shown; switch to scale 2 in chronic hypercapnic respiratory failure (target 88-92%).',
    version: '1.0',
    pin_default_for_roles: ['doctor', 'rmo', 'registrar', 'nurse', 'charge_nurse', 'emergency_physician'],
    source_citation: 'Royal College of Physicians. NEWS2: 2017 update.',
  },
  inputs: [
    { key: 'rr',            label: 'Respiratory rate',
      type: 'select', chart_source_path: 'vitals.rr_band',
      options: [
        { value: 'le_8',    label: '≤8 (3)' },
        { value: '9_11',    label: '9–11 (1)' },
        { value: '12_20',   label: '12–20 (0)' },
        { value: '21_24',   label: '21–24 (2)' },
        { value: 'ge_25',   label: '≥25 (3)' },
      ],
      display_order: 10 },
    { key: 'spo2',          label: 'SpO₂ (scale 1)',
      type: 'select', chart_source_path: 'vitals.spo2_band_s1',
      options: [
        { value: 'le_91',   label: '≤91% (3)' },
        { value: '92_93',   label: '92–93% (2)' },
        { value: '94_95',   label: '94–95% (1)' },
        { value: 'ge_96',   label: '≥96% (0)' },
      ],
      display_order: 20 },
    { key: 'supp_o2',       label: 'Supplemental oxygen',
      type: 'boolean', chart_source_path: 'vitals.on_oxygen',
      display_order: 30 },
    { key: 'sbp',           label: 'Systolic BP',
      type: 'select', chart_source_path: 'vitals.sbp_band',
      options: [
        { value: 'le_90',   label: '≤90 (3)' },
        { value: '91_100',  label: '91–100 (2)' },
        { value: '101_110', label: '101–110 (1)' },
        { value: '111_219', label: '111–219 (0)' },
        { value: 'ge_220',  label: '≥220 (3)' },
      ],
      display_order: 40 },
    { key: 'hr',            label: 'Heart rate',
      type: 'select', chart_source_path: 'vitals.hr_band',
      options: [
        { value: 'le_40',   label: '≤40 (3)' },
        { value: '41_50',   label: '41–50 (1)' },
        { value: '51_90',   label: '51–90 (0)' },
        { value: '91_110',  label: '91–110 (1)' },
        { value: '111_130', label: '111–130 (2)' },
        { value: 'ge_131',  label: '≥131 (3)' },
      ],
      display_order: 50 },
    { key: 'consciousness', label: 'Consciousness (ACVPU)',
      type: 'select', chart_source_path: 'neuro.acvpu',
      options: [
        { value: 'alert',       label: 'Alert (0)' },
        { value: 'not_alert',   label: 'New Confusion / V / P / U (3)' },
      ],
      display_order: 60 },
    { key: 'temp',          label: 'Temperature (°C)',
      type: 'select', chart_source_path: 'vitals.temp_band',
      options: [
        { value: 'le_35',   label: '≤35.0 (3)' },
        { value: '35p1_36', label: '35.1–36.0 (1)' },
        { value: '36p1_38', label: '36.1–38.0 (0)' },
        { value: '38p1_39', label: '38.1–39.0 (1)' },
        { value: 'ge_39p1', label: '≥39.1 (2)' },
      ],
      display_order: 70 },
  ],
  scoring: [
    { rule_type: 'sum', input_key: 'rr',            when_value: 'le_8',    points: 3, display_order: 10 },
    { rule_type: 'sum', input_key: 'rr',            when_value: '9_11',    points: 1, display_order: 11 },
    { rule_type: 'sum', input_key: 'rr',            when_value: '12_20',   points: 0, display_order: 12 },
    { rule_type: 'sum', input_key: 'rr',            when_value: '21_24',   points: 2, display_order: 13 },
    { rule_type: 'sum', input_key: 'rr',            when_value: 'ge_25',   points: 3, display_order: 14 },
    { rule_type: 'sum', input_key: 'spo2',          when_value: 'le_91',   points: 3, display_order: 20 },
    { rule_type: 'sum', input_key: 'spo2',          when_value: '92_93',   points: 2, display_order: 21 },
    { rule_type: 'sum', input_key: 'spo2',          when_value: '94_95',   points: 1, display_order: 22 },
    { rule_type: 'sum', input_key: 'spo2',          when_value: 'ge_96',   points: 0, display_order: 23 },
    { rule_type: 'sum', input_key: 'supp_o2',       points: 2, display_order: 30 },
    { rule_type: 'sum', input_key: 'sbp',           when_value: 'le_90',   points: 3, display_order: 40 },
    { rule_type: 'sum', input_key: 'sbp',           when_value: '91_100',  points: 2, display_order: 41 },
    { rule_type: 'sum', input_key: 'sbp',           when_value: '101_110', points: 1, display_order: 42 },
    { rule_type: 'sum', input_key: 'sbp',           when_value: '111_219', points: 0, display_order: 43 },
    { rule_type: 'sum', input_key: 'sbp',           when_value: 'ge_220',  points: 3, display_order: 44 },
    { rule_type: 'sum', input_key: 'hr',            when_value: 'le_40',   points: 3, display_order: 50 },
    { rule_type: 'sum', input_key: 'hr',            when_value: '41_50',   points: 1, display_order: 51 },
    { rule_type: 'sum', input_key: 'hr',            when_value: '51_90',   points: 0, display_order: 52 },
    { rule_type: 'sum', input_key: 'hr',            when_value: '91_110',  points: 1, display_order: 53 },
    { rule_type: 'sum', input_key: 'hr',            when_value: '111_130', points: 2, display_order: 54 },
    { rule_type: 'sum', input_key: 'hr',            when_value: 'ge_131',  points: 3, display_order: 55 },
    { rule_type: 'sum', input_key: 'consciousness', when_value: 'alert',     points: 0, display_order: 60 },
    { rule_type: 'sum', input_key: 'consciousness', when_value: 'not_alert', points: 3, display_order: 61 },
    { rule_type: 'sum', input_key: 'temp',          when_value: 'le_35',   points: 3, display_order: 70 },
    { rule_type: 'sum', input_key: 'temp',          when_value: '35p1_36', points: 1, display_order: 71 },
    { rule_type: 'sum', input_key: 'temp',          when_value: '36p1_38', points: 0, display_order: 72 },
    { rule_type: 'sum', input_key: 'temp',          when_value: '38p1_39', points: 1, display_order: 73 },
    { rule_type: 'sum', input_key: 'temp',          when_value: 'ge_39p1', points: 2, display_order: 74 },
  ],
  bands: [
    { band_key: 'low',      label: 'Low (routine)',       min_score: 0, max_score: 0,    color: 'green',  interpretation_default: 'Routine monitoring (min. 12-hourly).', display_order: 10 },
    { band_key: 'low_med',  label: 'Low-medium',          min_score: 1, max_score: 4,    color: 'yellow', interpretation_default: 'Increase observations to min. 4–6-hourly; ward nurse review.', display_order: 20 },
    { band_key: 'medium',   label: 'Medium (urgent)',     min_score: 5, max_score: 6,    color: 'yellow', interpretation_default: 'Urgent review by clinician with acute-care competencies. Observations at least hourly.', display_order: 30 },
    { band_key: 'high',     label: 'High (emergency)',    min_score: 7, max_score: null, color: 'red',    interpretation_default: 'Emergency assessment by critical-care team. Continuous monitoring. Consider ICU transfer.', display_order: 40 },
  ],
};

// ─── 8. qSOFA ──────────────────────────────────────────────────
const QSOFA: CalcFixture = {
  def: {
    slug: 'qsofa',
    name: 'qSOFA',
    specialty: 'critical_care',
    short_description: 'Quick bedside sepsis risk stratification.',
    long_description: 'Bedside prompt flagging adult patients with suspected infection who are at increased risk of poor outcome. ≥2 of 3 criteria = high risk; full SOFA + lactate next.',
    version: '1.0',
    pin_default_for_roles: ['doctor', 'rmo', 'registrar', 'emergency_physician', 'intensivist', 'nurse', 'charge_nurse'],
    source_citation: 'Singer M et al. JAMA 2016;315:801-10 (Sepsis-3).',
  },
  inputs: [
    { key: 'rr_ge_22',       label: 'Respiratory rate ≥22',           type: 'boolean', chart_source_path: 'vitals.rr_ge_22', display_order: 10 },
    { key: 'altered_mental', label: 'Altered mental status (GCS <15)', type: 'boolean', chart_source_path: 'neuro.gcs_lt_15', display_order: 20 },
    { key: 'sbp_le_100',     label: 'Systolic BP ≤100 mmHg',          type: 'boolean', chart_source_path: 'vitals.sbp_le_100', display_order: 30 },
  ],
  scoring: [
    { rule_type: 'sum', input_key: 'rr_ge_22',       points: 1, display_order: 10 },
    { rule_type: 'sum', input_key: 'altered_mental', points: 1, display_order: 20 },
    { rule_type: 'sum', input_key: 'sbp_le_100',     points: 1, display_order: 30 },
  ],
  bands: [
    { band_key: 'low',      label: 'Low',      min_score: 0, max_score: 1,    color: 'green',  interpretation_default: 'qSOFA not suggestive of high risk of poor outcome. Continue usual care; re-assess if clinical change.', display_order: 10 },
    { band_key: 'elevated', label: 'Elevated', min_score: 2, max_score: 2,    color: 'yellow', interpretation_default: 'Increased risk of poor outcome. Measure lactate; calculate full SOFA; begin sepsis workup + antibiotics if infection suspected.', display_order: 20 },
    { band_key: 'high',     label: 'High',     min_score: 3, max_score: null, color: 'red',    interpretation_default: 'High risk of poor outcome. Immediate senior review, urgent sepsis bundle, consider ICU.', display_order: 30 },
  ],
};

// ─── 9. Child-Pugh ─────────────────────────────────────────────
const CHILD_PUGH: CalcFixture = {
  def: {
    slug: 'child-pugh',
    name: 'Child-Pugh Score',
    specialty: 'gastroenterology',
    short_description: 'Severity of chronic liver disease (cirrhosis).',
    long_description: 'Classifies severity of cirrhosis (A/B/C). Guides surgical risk, prognosis, and transplant candidacy. Uses 5 variables: total bilirubin, serum albumin, INR, ascites, hepatic encephalopathy.',
    version: '1.0',
    pin_default_for_roles: ['doctor', 'rmo', 'registrar', 'consultant', 'gastroenterologist', 'hepatologist'],
    source_citation: 'Pugh RN et al. Br J Surg 1973;60:646-9.',
  },
  inputs: [
    { key: 'bilirubin', label: 'Total bilirubin (mg/dL)',
      type: 'select', chart_source_path: 'labs.bilirubin_band',
      options: [
        { value: 'lt_2',    label: '<2 (1)' },
        { value: '2_to_3',  label: '2–3 (2)' },
        { value: 'gt_3',    label: '>3 (3)' },
      ],
      display_order: 10 },
    { key: 'albumin',  label: 'Serum albumin (g/dL)',
      type: 'select', chart_source_path: 'labs.albumin_band',
      options: [
        { value: 'gt_3p5',    label: '>3.5 (1)' },
        { value: '2p8_to_3p5',label: '2.8–3.5 (2)' },
        { value: 'lt_2p8',    label: '<2.8 (3)' },
      ],
      display_order: 20 },
    { key: 'inr',      label: 'INR',
      type: 'select', chart_source_path: 'labs.inr_band',
      options: [
        { value: 'lt_1p7',    label: '<1.7 (1)' },
        { value: '1p7_to_2p3',label: '1.7–2.3 (2)' },
        { value: 'gt_2p3',    label: '>2.3 (3)' },
      ],
      display_order: 30 },
    { key: 'ascites', label: 'Ascites',
      type: 'select',
      options: [
        { value: 'none',       label: 'None (1)' },
        { value: 'mild',       label: 'Mild / diuretic-responsive (2)' },
        { value: 'mod_severe', label: 'Moderate–severe / diuretic-refractory (3)' },
      ],
      display_order: 40 },
    { key: 'enceph',  label: 'Hepatic encephalopathy',
      type: 'select',
      options: [
        { value: 'none',       label: 'None (1)' },
        { value: 'grade_1_2',  label: 'Grade 1–2 / suppressed with medication (2)' },
        { value: 'grade_3_4',  label: 'Grade 3–4 / refractory (3)' },
      ],
      display_order: 50 },
  ],
  scoring: [
    { rule_type: 'sum', input_key: 'bilirubin', when_value: 'lt_2',        points: 1, display_order: 10 },
    { rule_type: 'sum', input_key: 'bilirubin', when_value: '2_to_3',      points: 2, display_order: 11 },
    { rule_type: 'sum', input_key: 'bilirubin', when_value: 'gt_3',        points: 3, display_order: 12 },
    { rule_type: 'sum', input_key: 'albumin',   when_value: 'gt_3p5',      points: 1, display_order: 20 },
    { rule_type: 'sum', input_key: 'albumin',   when_value: '2p8_to_3p5', points: 2, display_order: 21 },
    { rule_type: 'sum', input_key: 'albumin',   when_value: 'lt_2p8',      points: 3, display_order: 22 },
    { rule_type: 'sum', input_key: 'inr',       when_value: 'lt_1p7',      points: 1, display_order: 30 },
    { rule_type: 'sum', input_key: 'inr',       when_value: '1p7_to_2p3', points: 2, display_order: 31 },
    { rule_type: 'sum', input_key: 'inr',       when_value: 'gt_2p3',      points: 3, display_order: 32 },
    { rule_type: 'sum', input_key: 'ascites',   when_value: 'none',        points: 1, display_order: 40 },
    { rule_type: 'sum', input_key: 'ascites',   when_value: 'mild',        points: 2, display_order: 41 },
    { rule_type: 'sum', input_key: 'ascites',   when_value: 'mod_severe',  points: 3, display_order: 42 },
    { rule_type: 'sum', input_key: 'enceph',    when_value: 'none',        points: 1, display_order: 50 },
    { rule_type: 'sum', input_key: 'enceph',    when_value: 'grade_1_2',   points: 2, display_order: 51 },
    { rule_type: 'sum', input_key: 'enceph',    when_value: 'grade_3_4',   points: 3, display_order: 52 },
  ],
  bands: [
    { band_key: 'class_a', label: 'Class A (well-compensated)',    min_score: 5,  max_score: 6,  color: 'green',  interpretation_default: '1-year survival ~100%, 2-year ~85%. Well-compensated cirrhosis; typically tolerates major surgery.', display_order: 10 },
    { band_key: 'class_b', label: 'Class B (significant compromise)', min_score: 7,  max_score: 9,  color: 'yellow', interpretation_default: '1-year survival ~81%, 2-year ~57%. Significant functional compromise; elective surgery carries meaningful risk.', display_order: 20 },
    { band_key: 'class_c', label: 'Class C (decompensated)',          min_score: 10, max_score: 15, color: 'red',    interpretation_default: '1-year survival ~45%, 2-year ~35%. Decompensated cirrhosis — transplant evaluation; avoid elective surgery.', display_order: 30 },
  ],
};

// ─── 10. MELD (banded v1 — full formula ships in PC.2c) ────────
const MELD_BANDED: CalcFixture = {
  def: {
    slug: 'meld-banded-v1',
    name: 'MELD (banded v1)',
    specialty: 'gastroenterology',
    short_description: 'Banded proxy for end-stage liver disease (v1).',
    long_description: 'PC.2a ships a banded approximation of MELD because the scoring engine has no logarithm primitive. Each of creatinine, bilirubin, and INR maps to a coarse point bucket; the sum roughly tracks MELD risk categories (low / moderate / high / very high). The exact formula 9.57·ln(Cr) + 3.78·ln(Bili) + 11.2·ln(INR) + 6.43 ships in PC.2c. Use cautiously and correlate with the full MELD-Na once available.',
    version: '1.0',
    pin_default_for_roles: ['doctor', 'gastroenterologist', 'hepatologist', 'consultant'],
    source_citation: 'Kamath PS et al. Hepatology 2001;33:464-70. Banded adaptation for Even OS v1.',
  },
  inputs: [
    { key: 'creatinine',  label: 'Serum creatinine (mg/dL) — or dialysis',
      type: 'select', chart_source_path: 'labs.creatinine_band',
      options: [
        { value: 'lt_1',       label: '<1.0' },
        { value: '1_to_2',     label: '1.0–2.0' },
        { value: '2_to_4',     label: '2.0–4.0' },
        { value: 'gt_4_or_dx', label: '>4.0 or dialysis ≥2× / week' },
      ],
      display_order: 10 },
    { key: 'bilirubin',  label: 'Total bilirubin (mg/dL)',
      type: 'select', chart_source_path: 'labs.bilirubin_band',
      options: [
        { value: 'lt_1',   label: '<1.0' },
        { value: '1_to_2', label: '1.0–2.0' },
        { value: '2_to_4', label: '2.0–4.0' },
        { value: '4_to_10',label: '4.0–10.0' },
        { value: 'gt_10',  label: '>10.0' },
      ],
      display_order: 20 },
    { key: 'inr',        label: 'INR',
      type: 'select', chart_source_path: 'labs.inr_band',
      options: [
        { value: 'lt_1p3',    label: '<1.3' },
        { value: '1p3_to_1p7',label: '1.3–1.7' },
        { value: '1p7_to_2p5',label: '1.7–2.5' },
        { value: 'gt_2p5',    label: '>2.5' },
      ],
      display_order: 30 },
  ],
  scoring: [
    { rule_type: 'sum', input_key: 'creatinine', when_value: 'lt_1',        points: 0,  display_order: 10 },
    { rule_type: 'sum', input_key: 'creatinine', when_value: '1_to_2',      points: 4,  display_order: 11 },
    { rule_type: 'sum', input_key: 'creatinine', when_value: '2_to_4',      points: 8,  display_order: 12 },
    { rule_type: 'sum', input_key: 'creatinine', when_value: 'gt_4_or_dx',  points: 13, display_order: 13 },
    { rule_type: 'sum', input_key: 'bilirubin',  when_value: 'lt_1',        points: 0,  display_order: 20 },
    { rule_type: 'sum', input_key: 'bilirubin',  when_value: '1_to_2',      points: 3,  display_order: 21 },
    { rule_type: 'sum', input_key: 'bilirubin',  when_value: '2_to_4',      points: 6,  display_order: 22 },
    { rule_type: 'sum', input_key: 'bilirubin',  when_value: '4_to_10',     points: 9,  display_order: 23 },
    { rule_type: 'sum', input_key: 'bilirubin',  when_value: 'gt_10',       points: 13, display_order: 24 },
    { rule_type: 'sum', input_key: 'inr',        when_value: 'lt_1p3',      points: 0,  display_order: 30 },
    { rule_type: 'sum', input_key: 'inr',        when_value: '1p3_to_1p7',  points: 3,  display_order: 31 },
    { rule_type: 'sum', input_key: 'inr',        when_value: '1p7_to_2p5',  points: 6,  display_order: 32 },
    { rule_type: 'sum', input_key: 'inr',        when_value: 'gt_2p5',      points: 9,  display_order: 33 },
  ],
  bands: [
    { band_key: 'low',       label: 'Low (MELD ~<10)',        min_score: 0,  max_score: 9,  color: 'green',  interpretation_default: '3-month mortality ~2%. Low ESLD severity band. Confirm with full MELD-Na (available PC.2c).', display_order: 10 },
    { band_key: 'moderate',  label: 'Moderate (MELD 10–19)',  min_score: 10, max_score: 19, color: 'yellow', interpretation_default: '3-month mortality ~6%. Optimise and monitor. Confirm with full MELD-Na.', display_order: 20 },
    { band_key: 'high',      label: 'High (MELD 20–29)',      min_score: 20, max_score: 29, color: 'yellow', interpretation_default: '3-month mortality ~20%. Transplant referral if not already. Confirm with full MELD-Na.', display_order: 30 },
    { band_key: 'very_high', label: 'Very high (MELD ≥30)',   min_score: 30, max_score: null, color: 'red',  interpretation_default: '3-month mortality ~50%. Urgent transplant evaluation / ICU-level support. Confirm with full MELD-Na.', display_order: 40 },
  ],
};


// ─── 11. MELD 3.0 (2022 UNOS — exact formula via named-formula registry) ────
// PC.2c1: uses formula_ref dispatch. The scoring engine skips rules and
// calls meld_3_0() with the raw inputs (bilirubin, INR, creatinine, albumin,
// sodium, sex, on_dialysis). Bands mirror UNOS allocation tiers.
const MELD_3_0: CalcFixture = {
  def: {
    slug: 'meld-3-0',
    name: 'MELD 3.0 (2022 UNOS)',
    specialty: 'gastroenterology',
    short_description: 'Exact MELD 3.0 (sex + albumin adjusted) — used for U.S. liver allocation.',
    long_description: 'MELD 3.0 is the 2022 OPTN/UNOS score for liver-allocation priority. It extends MELD-Na with sex and albumin adjustments (Kim WR et al., Gastroenterology 2021). Clamps applied per UNOS rules: creatinine [1.0-3.0], bilirubin ≥1.0, INR ≥1.0, albumin [1.5-3.5], sodium [125-137]. Patients on dialysis ≥2×/week or 24h CVVH use Cr=3.0. Final score clamped to [6, 40]. Scoring is deterministic, server-side, via the named-formula registry (formula_ref: meld_3_0).',
    version: '1.0',
    pin_default_for_roles: ['doctor', 'gastroenterologist', 'hepatologist', 'consultant'],
    source_citation: 'Kim WR et al. Gastroenterology 2021;161:1887-1895. doi:10.1053/j.gastro.2021.08.050. OPTN policy eff. 2023-07-11.',
    formula_ref: 'meld_3_0',
  },
  inputs: [
    { key: 'sex', label: 'Sex',
      type: 'select', chart_source_path: 'patient.sex',
      options: [
        { value: 'female', label: 'Female (+1.33)' },
        { value: 'male', label: 'Male' },
      ],
      display_order: 10 },
    { key: 'on_dialysis', label: 'On dialysis ≥2×/week or 24h CVVH?',
      type: 'boolean', helper_text: 'If true, creatinine is forced to 3.0 mg/dL per UNOS rules.',
      display_order: 20 },
    { key: 'creatinine', label: 'Serum creatinine (mg/dL)',
      type: 'number', unit: 'mg/dL', chart_source_path: 'labs.creatinine',
      options: { min: 0.1, max: 20, step: 0.1 },
      helper_text: 'Clamped to [1.0, 3.0] by formula.', display_order: 30 },
    { key: 'bilirubin', label: 'Total bilirubin (mg/dL)',
      type: 'number', unit: 'mg/dL', chart_source_path: 'labs.bilirubin',
      options: { min: 0.1, max: 50, step: 0.1 },
      helper_text: 'Clamped to ≥1.0 by formula.', display_order: 40 },
    { key: 'inr', label: 'INR',
      type: 'number', chart_source_path: 'labs.inr',
      options: { min: 0.5, max: 10, step: 0.1 },
      helper_text: 'Clamped to ≥1.0 by formula.', display_order: 50 },
    { key: 'albumin', label: 'Serum albumin (g/dL)',
      type: 'number', unit: 'g/dL', chart_source_path: 'labs.albumin',
      options: { min: 1.0, max: 5.5, step: 0.1 },
      helper_text: 'Clamped to [1.5, 3.5] by formula.', display_order: 60 },
    { key: 'sodium', label: 'Serum sodium (mEq/L)',
      type: 'number', unit: 'mEq/L', chart_source_path: 'labs.sodium',
      options: { min: 100, max: 155, step: 1 },
      helper_text: 'Clamped to [125, 137] by formula.', display_order: 70 },
  ],
  scoring: [
    // No rules — scoring is entirely via the named formula. Keeping this
    // array empty is valid; runCalculator dispatches to FORMULAS.meld_3_0.
  ],
  bands: [
    { band_key: 'low',       label: 'Low (MELD <10)',          min_score: 6,  max_score: 9,  color: 'green',  interpretation_default: '3-month mortality ~2%. Low ESLD severity. Routine follow-up.', display_order: 10 },
    { band_key: 'moderate',  label: 'Moderate (MELD 10-19)',   min_score: 10, max_score: 19, color: 'yellow', interpretation_default: '3-month mortality ~6%. Optimise and monitor. Consider transplant referral if decompensated.', display_order: 20 },
    { band_key: 'high',      label: 'High (MELD 20-29)',       min_score: 20, max_score: 29, color: 'yellow', interpretation_default: '3-month mortality ~20%. Transplant evaluation if not already in progress.', display_order: 30 },
    { band_key: 'very_high', label: 'Very high (MELD 30-39)',  min_score: 30, max_score: 39, color: 'red',    interpretation_default: '3-month mortality ~50%. Urgent transplant evaluation / ICU-level support.', display_order: 40 },
    { band_key: 'critical',  label: 'Critical (MELD 40)',      min_score: 40, max_score: 40, color: 'red',    interpretation_default: '3-month mortality ~70%. Status 1A/exception territory; immediate transplant team involvement.', display_order: 50 },
  ],
};

// ─── Export ────────────────────────────────────────────────────
export const CALCULATOR_FIXTURES: CalcFixture[] = [
  CHA2DS2_VASC,
  HAS_BLED,
  HEART_SCORE,
  WELLS_DVT,
  WELLS_PE,
  GCS,
  NEWS2,
  QSOFA,
  CHILD_PUGH,
  MELD_BANDED,
  MELD_3_0,
];
