/**
 * Even AI Types
 * Complete TypeScript interface definitions for the Even AI module (Module 18)
 * Matches database schema and API contracts across all components
 */

// ============================================================================
// Module & Severity Types
// ============================================================================

export type AIModule = 'billing' | 'clinical' | 'quality' | 'operations' | 'pharmacy' | 'lab' | 'ot' | 'admin';

export type CardCategory = 'alert' | 'suggestion' | 'prediction' | 'report' | 'nudge';

export type CardSeverity = 'critical' | 'high' | 'medium' | 'low' | 'info';

export type CardStatus = 'active' | 'dismissed' | 'acted_on' | 'expired';

export type CardSource = 'llm' | 'template' | 'hybrid';

export type RequestStatus = 'pending' | 'processing' | 'completed' | 'failed';

export type QueuePriority = 'critical' | 'high' | 'medium' | 'low';

export type AuditLogStatus = 'success' | 'error' | 'timeout';

export type TriggeredBy = 'cron' | 'manual' | 'event' | 'template';

export type RuleSource = 'manual' | 'learned';

export type HealthStatus = 'online' | 'offline' | 'degraded';

// ============================================================================
// Insight Cards (ai_insight_cards table)
// ============================================================================

/**
 * InsightCard
 * Universal AI output type representing a single insight/alert/suggestion/prediction
 * generated by the Even AI background layer. Cards are targeted to specific users
 * or roles and can be acted upon, dismissed, or expired.
 */
export interface InsightCard {
  id: string;
  hospital_id: string;
  module: AIModule;
  category: CardCategory;
  severity: CardSeverity;

  title: string;
  body: string;
  explanation: string;
  data_sources: string[];
  suggested_action?: string;
  action_url?: string;

  confidence: number; // 0-1
  source: CardSource;
  model_version?: string;

  audit_log_id?: string;
  status: CardStatus;

  target_user_id?: string;
  target_role?: string;
  target_encounter_id?: string;
  target_patient_id?: string;

  expires_at?: string | null;
  dismissed_by?: string | null;
  dismissed_at?: string | null;
  acted_on_by?: string | null;
  acted_on_at?: string | null;

  feedback_score?: -1 | 0 | 1 | null;
  feedback_note?: string | null;

  created_at: string;
  updated_at: string;
}

// ============================================================================
// Audit Log (ai_audit_log table)
// ============================================================================

/**
 * AuditLogEntry
 * Complete record of every LLM inference request/response for traceability,
 * debugging, and model improvement. Tracks latency, tokens, errors, and trigger source.
 */
export interface AuditLogEntry {
  id: string;
  hospital_id: string;
  module: AIModule;

  prompt_text: string;
  prompt_tokens?: number;
  response_text: string;
  response_tokens?: number;

  model: string;
  latency_ms: number;
  status: AuditLogStatus;
  error_message?: string | null;

  input_data_hash?: string;
  triggered_by: TriggeredBy;
  user_id?: string | null;

  created_at: string;
}

// ============================================================================
// Request Queue (ai_request_queue table)
// ============================================================================

/**
 * QueueItem
 * Background LLM request queued for processing. Implements exponential backoff
 * retry logic and tracks processing state across multiple attempts.
 */
export interface QueueItem {
  id: string;
  hospital_id: string;
  module: AIModule;
  priority: QueuePriority;

  input_data: Record<string, any>;
  prompt_template: string;
  status: RequestStatus;

  attempts: number;
  max_attempts: number;
  last_attempt_at?: string | null;
  error_message?: string | null;
  result_card_id?: string | null;

  created_at: string;
  process_after: string;
}

// ============================================================================
// Claim Predictions (claim_predictions table)
// ============================================================================

/**
 * ClaimPrediction
 * ML prediction for claim approval, amount, and deductions. Used by the
 * billing module to forecast cash flow and identify high-risk claims.
 */
export interface ClaimPrediction {
  id: string;
  hospital_id: string;
  encounter_id: string;
  claim_id?: string | null;
  tpa_name: string;
  procedure_category?: string | null;

  predicted_amount: number;
  predicted_approval: number;
  predicted_approval_pct: number;
  predicted_deductions: Array<{
    type: string;
    amount: number;
    reason: string;
  }>;

  confidence: number;
  source: CardSource;

  actual_claim_amount?: number | null;
  actual_approved_amount?: number | null;
  actual_deductions?: number | null;
  settlement_date?: string | null;
  prediction_accuracy?: number | null;

  created_at: string;
}

// ============================================================================
// Claim Rubric (claim_rubrics table)
// ============================================================================

/**
 * ClaimRubric
 * Rules learned or manually configured for claim approval patterns per TPA.
 * Evolves over time as actual claim outcomes are observed.
 */
export interface ClaimRubric {
  id: string;
  hospital_id: string;
  tpa_name: string;
  procedure_category?: string | null;
  rule_type: string;
  rule_data: Record<string, any>;

  confidence: number;
  source: RuleSource;
  is_active: boolean;

  created_at: string;
  updated_at: string;
}

// ============================================================================
// NABH Readiness (nabh_readiness_scores table)
// ============================================================================

/**
 * NabhReadinessScore
 * AI-generated compliance readiness assessment against NABH standards.
 * Identifies top gaps and generates action items for quality improvement.
 */
export interface NabhReadinessScore {
  id: string;
  hospital_id: string;
  score_date: string;
  overall_score: number;
  chapter_scores: Record<string, number>;

  top_gaps: Array<{
    chapter: string;
    gap: string;
    recommendation: string;
  }>;
  action_items_generated: boolean;

  source: CardSource;
  audit_log_id?: string | null;

  created_at: string;
}

// ============================================================================
// Bed Predictions (bed_predictions table)
// ============================================================================

/**
 * BedPrediction
 * Forecasts when a patient bed will become available based on clinical
 * factors and historical discharge patterns. Supports operations planning.
 */
export interface BedPrediction {
  id: string;
  hospital_id: string;
  bed_id: string;
  encounter_id: string;
  predicted_discharge_at: string;
  confidence: number;

  factors: Array<{
    factor: string;
    weight: number;
    value: any;
  }>;

  actual_discharge_at?: string | null;
  prediction_error_hours?: number | null;

  source: CardSource;
  created_at: string;
}

// ============================================================================
// Template Rules (ai_template_rules table)
// ============================================================================

/**
 * TemplateRule
 * Rule-based card generation without LLM inference. Triggered by conditions
 * (e.g., "all OT procedures overrun → generate alert"). Fallback when LLM is offline.
 */
export interface TemplateRule {
  id: string;
  hospital_id: string;
  module: AIModule;
  rule_name: string;
  trigger_type: string;
  condition_config: Record<string, any>;

  card_template: Record<string, any>;
  priority: QueuePriority;
  is_active: boolean;
  fire_count: number;
  last_fired_at?: string | null;

  created_at: string;
  updated_at: string;
}

// ============================================================================
// LLM Client Types
// ============================================================================

/**
 * LLMRequest
 * Input contract for the underlying LLM client (OpenAI or Ollama).
 */
export interface LLMRequest {
  system_prompt: string;
  user_prompt: string;
  max_tokens?: number;
  temperature?: number;
}

/**
 * LLMResponse
 * Output contract from the LLM client with usage metrics and latency.
 */
export interface LLMResponse {
  content: string;
  tokens_used: {
    prompt: number;
    completion: number;
  };
  latency_ms: number;
  model: string;
}

// ============================================================================
// Health & Observability Types
// ============================================================================

/**
 * AIHealth
 * Current operational health of the Even AI system. Returned by /api/ai/health.
 */
export interface AIHealth {
  llm_status: HealthStatus;
  llm_latency_ms: number;
  model: string;
  queue_depth: number;
  cards_generated_today: number;
  last_successful_inference: string | null;
}

/**
 * QueueStatus
 * Current state of the background request queue.
 */
export interface QueueStatus {
  pending: number;
  processing: number;
  failed: number;
  oldest_pending_age_minutes: number;
}

/**
 * AIObservatory
 * Complete observability dashboard response. Aggregates health, latency trends,
 * request distribution, card metrics, and queue status for /admin/ai/observatory.
 */
export interface AIObservatory {
  health: AIHealth;
  latency_trend: Array<{
    timestamp: string;
    p50: number;
    p95: number;
  }>;
  requests_by_module: Array<{
    module: AIModule;
    count: number;
    avg_latency: number;
  }>;
  cards_by_status: Array<{
    status: CardStatus;
    count: number;
  }>;
  cards_by_module: Array<{
    module: AIModule;
    count: number;
  }>;
  feedback_summary: {
    helpful: number;
    not_helpful: number;
    neutral: number;
  };
  queue_status: QueueStatus;
  top_template_rules: Array<{
    rule_name: string;
    fire_count: number;
  }>;
}

// ============================================================================
// Background Job Types
// ============================================================================

/**
 * JobResult
 * Response from background job execution (via cron or manual trigger).
 * Returned by /api/ai/jobs/{jobName}.
 */
export interface JobResult {
  job: string;
  status: 'completed' | 'partial' | 'skipped';
  cards_generated: number;
  errors: number;
  duration_ms: number;
  details?: string;
}

// ============================================================================
// API Request/Response Wrappers
// ============================================================================

/**
 * CardFeedbackRequest
 * Payload to submit user feedback on an insight card.
 */
export interface CardFeedbackRequest {
  card_id: string;
  score: -1 | 0 | 1;
  note?: string;
}

/**
 * CardDismissRequest
 * Payload to dismiss an insight card.
 */
export interface CardDismissRequest {
  card_id: string;
}

/**
 * CardActionRequest
 * Payload to mark a card as acted-upon.
 */
export interface CardActionRequest {
  card_id: string;
}
