import { NextRequest, NextResponse } from 'next/server';
import { neon } from '@neondatabase/serverless';
import { generateInsight } from '@/lib/ai/llm-client';
import { processIngestDocument } from '@/lib/document-ingest/worker';

let _sql: any = null;
function getSql() {
  if (!_sql) _sql = neon(process.env.DATABASE_URL!);
  return _sql;
}

export async function POST(req: NextRequest) {
  const startTime = Date.now();

  try {
    const adminKey = req.headers.get('x-admin-key');
    if (adminKey !== process.env.ADMIN_KEY) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const sql = getSql();
    let cardsGenerated = 0;
    let errors = 0;

    // Get pending queue items (limit 10)
    let queueItems: any[] = [];
    try {
      queueItems = await sql(
        `SELECT id, hospital_id, module, priority, input_data, prompt_template, attempts, max_attempts
         FROM ai_request_queue
         WHERE status = 'pending' AND process_after <= NOW()
         ORDER BY CASE priority WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 ELSE 4 END, created_at ASC
         LIMIT 10`
      );
    } catch (err: any) {
      if (err.message?.includes('does not exist')) {
        const duration_ms = Date.now() - startTime;
        return NextResponse.json({
          job: 'process-queue',
          status: 'skipped' as const,
          cards_generated: 0,
          errors: 0,
          duration_ms,
          details: 'ai_request_queue table not found',
        });
      }
      throw err;
    }

    if (queueItems.length === 0) {
      const duration_ms = Date.now() - startTime;
      return NextResponse.json({
        job: 'process-queue',
        status: 'completed' as const,
        cards_generated: 0,
        errors: 0,
        duration_ms,
        details: 'No pending items',
      });
    }

    // Process each queue item
    for (const item of queueItems) {
      try {
        // Mark as processing
        await sql(
          `UPDATE ai_request_queue SET status = 'processing', last_attempt_at = NOW() WHERE id = $1`,
          [item.id]
        );

        // ─────────────────────────────────────────────────────────
        // N.4 — ingest_document branch.
        // Routes to the document-ingest worker, which reads the
        // mrd_document_references row, extracts text, calls the LLM,
        // writes chart_update_proposals, and auto-accepts safe high-
        // confidence items into canonical clinical tables.
        // ─────────────────────────────────────────────────────────
        if (item.prompt_template === 'ingest_document') {
          const ingestRes = await processIngestDocument(sql, {
            id: item.id,
            hospital_id: item.hospital_id,
            input_data: item.input_data,
            attempts: item.attempts || 0,
            max_attempts: item.max_attempts || 3,
          });
          if (ingestRes.ok) {
            await sql(
              `UPDATE ai_request_queue SET status = 'completed', last_attempt_at = NOW() WHERE id = $1`,
              [item.id]
            );
            cardsGenerated++; // counted alongside insight cards for the cron summary
            continue;
          }
          // Fall through to error handler with the worker's error message.
          throw new Error(ingestRes.error || 'ingest_document failed');
        }

        const inputData = typeof item.input_data === 'string' ? JSON.parse(item.input_data) : item.input_data;

        // Build prompt from template and input data
        const systemPrompt = `You are Even AI, an advisory intelligence layer for hospital operations. Generate a concise insight card for the ${item.module} module. Be specific, actionable, and data-driven.`;
        const userPrompt = `Template: ${item.prompt_template}\n\nContext data:\n${JSON.stringify(inputData, null, 2)}\n\nGenerate a brief, actionable insight based on this data.`;

        // Attempt LLM call
        const response = await generateInsight({
          hospital_id: item.hospital_id,
          module: item.module,
          system_prompt: systemPrompt,
          user_prompt: userPrompt,
          max_tokens: 500,
          temperature: 0.7,
          triggered_by: 'cron',
        });

        if (response) {
          // Create insight card from LLM response
          await sql(
            `INSERT INTO ai_insight_cards (
              hospital_id, module, category, severity, title, body, explanation,
              data_sources, confidence, source, model_version, status, expires_at
            ) VALUES (
              $1, $2, 'suggestion', 'medium', $3, $4, $5,
              '[]'::jsonb, 0.75, 'llm', $6, 'active', NOW() + INTERVAL '7 days'
            )`,
            [
              item.hospital_id,
              item.module,
              `AI Insight — ${item.module}`,
              response.content.substring(0, 2000),
              `Generated by LLM from queue item ${item.id}`,
              response.model,
            ]
          );

          // Mark queue item as completed
          await sql(
            `UPDATE ai_request_queue SET status = 'completed', result_card_id = NULL, last_attempt_at = NOW() WHERE id = $1`,
            [item.id]
          );

          cardsGenerated++;
        } else {
          throw new Error('LLM returned no response');
        }
      } catch (error) {
        errors++;
        const errorMsg = error instanceof Error ? error.message : 'Unknown error';
        const newAttempts = (item.attempts || 0) + 1;
        const maxAttempts = item.max_attempts || 3;

        const newStatus = newAttempts >= maxAttempts ? 'failed' : 'pending';

        try {
          await sql(
            `UPDATE ai_request_queue
             SET attempts = $1, status = $2, error_message = $3, last_attempt_at = NOW()
             WHERE id = $4`,
            [newAttempts, newStatus, errorMsg, item.id]
          );
        } catch (e) {
          console.error(`Error updating queue item ${item.id}:`, e);
        }

        console.error(`Error processing queue item ${item.id}:`, error);
      }
    }

    const duration_ms = Date.now() - startTime;

    return NextResponse.json({
      job: 'process-queue',
      status: errors === 0 ? 'completed' as const : 'partial' as const,
      cards_generated: cardsGenerated,
      errors,
      duration_ms,
      details: `Processed ${queueItems.length} queue items`,
    });
  } catch (error) {
    const duration_ms = Date.now() - startTime;
    console.error('Process queue job failed:', error);

    return NextResponse.json(
      {
        job: 'process-queue',
        status: 'skipped' as const,
        cards_generated: 0,
        errors: 1,
        duration_ms,
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
